---
abstract: 'create a human-readable compressed string suitable for shell brace expansion'
author:
  - 'Alex White <VVu@geekfarm.org>'
generated_by: 'Dist::Zilla version 1.092680'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Compress-BraceExpansion
requires:
  Class::Std::Utils: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  Test::More: 0
version: 0.1.7
